language: ruby
sudo: false
rvm:
  - 2.3.1
  - 1.9.3
  - jruby-19mode
addons:
  apt:
    sources:
    - git-core
    packages:
    - git
git:
  depth: 10
before_install:
  - git --version
  - gem update bundler
